# site settings
title: Enrich Education 
description: Primary & High School Tutoring 
baseurl: /
url: "https://enricheducation.github.io"
author: 
city:
state:
zip_code:
country:
phone: 0430089992

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: EnrichEdu
github_url: EnrichEducation
gitlab_url:
googleplus_url:
instagram_url: EnrichEdu
linkedin_url:
pinterest_url:
slack_url: EnrichFamily
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
